インデントを調整する処理を実装
mimosa-project/emformat pull request #10
Opened 2023-04-16 09:10 UTC by raylicola

# 概要
- 入力ファイルの行ごとのインデント数を決定する機能を実装
- 仕様はIssueの通りです

# 関連するIssue
- close #5

2023-04-19 04:54 UTC, aabaa requested changes

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +def determine_indentation_numbers(tokens_by_line):
```python
determine_indentation_numbers(tokens_by_line) -> list[int]:
```

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +def determine_environ_part_indentation_numbers(environ_part_tokens):
environ_part_tokensが行単位のリストであることが分かるように名称変更する

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +def determine_environ_part_indentation_numbers(environ_part_tokens):
環境部についてはトークン毎にループを回して，改行処理とインデント処理を入れる．
この際，::によるコメント行以外の既存の改行は無視して良い．

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +def determine_body_part_indentation_numbers(body_part_tokens):
body_part_tokensが行単位のリストであることが分かるように名称変更する

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +        ):
beginの前に改行が入っていることを前提とした処理であることをコメントで明示する

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +    current_block = ""
current_block -> current_block_type

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +        ):
USE_INDENT_TAGSに属するブロック開始・終了関連のキーワードも同様に，前に改行が入っていることを前提とした処理が入っているため，先に関数の雛形だけでも作っておく

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +                    current_indentation_step += 1
```python
if current_block == "theorem" and first_token_text == "proof":
```

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +                if first_token_text == "proof":
こちらも同様

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +            current_block_level = 1
current_block_levelが0でなければエラーを出すほうが良い

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +        # Schemeブロック内で最初に出現する "proof" は "end" と対にならないため、ブロック内にいるどうか判定が必要
コメントを直す

2023-04-19 04:54 UTC, aabaa commented on src/miz_format.py
> +        if first_token_text in option.USE_INDENT_TAGS:
option.USE_INDENT_TAGSで以下のケースではエラー処理を入れたい
- theorem/scheme/definition/notationなどのブロック開始時にインデントが0より大きい場合
- endでインデントが既に0となっている場合

2023-04-26 06:09 UTC, aabaa approved these changes

2023-04-26 09:44 UTC, aabaa requested changes

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +                    current_indentation_step -= 1
current_indentation_step -> current_indentation_level

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
>          if first_token_text in option.USE_INDENT_TAGS:
USE_INDENT_TAGS -> INDENT_KEYWORDS

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +                indentation_numbers.append(
indentation_numbers -> indentation_widths

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +def determine_indentation_numbers(tokens_by_line) -> list[int]:
indentation_numbers -> indentation_widths

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +def determine_indentation_numbers(tokens_by_line) -> list[int]:
indentation_numbers -> indentation_widths

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +def convert_tokens_by_line_to_token_texts(tokens_by_line):
tokens_by_line -> token_lines : list[list[Token]]

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +    tokens_by_sentence = split_environ_part_tokens_into_sentences(tokens)
tokens_by_sentence -> token_sentences

2023-04-26 09:44 UTC, aabaa commented on src/settings.json
> +  "ENVIRON_IN_LINE_INDENTATION_SPACE_NUMBER": 6,
STANDARD_INDENTATION_WIDTH
ENVIRON_DIRECTIVE_INDENTATION_WIDTH
ENVIRON_LINE_INDENTATION_WIDTH

2023-04-26 09:44 UTC, aabaa commented on src/settings.json
> +  "ENVIRON_TAGS": [
ENV_DIRECTIVE_KEYWORDS

2023-04-26 09:44 UTC, aabaa commented on src/settings.json
> +  "USE_INDENT_TAGS": [
BLOCK_KEYWORDS

2023-04-26 09:44 UTC, aabaa commented on src/settings.json
> +  "TOP_OF_BLOCK_TAGS": [
TOP_BLOCK_KEYWORDS

2023-04-26 09:44 UTC, aabaa commented on src/settings.json
>    "USE_BEFORE_BLANK_LINE": [
KEYWORDS_INSERT_BLANK_LINE_BEFORE
KEYWORDS_INSERT_BLANK_LINE_AFTER

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +            current_line_length += 1
```python
    # 区切り位置を決定
    for token in directive_tokens:
        current_line_length += len(token.text)

        if current_line_length > option.MAX_LINE_LENGTH:
            # 次の行が[,|;]から開始しないようにする
            carryover_tokens = []
            if token.text in [",", ";"]:
                carryover_tokens.append(current_line_tokens.pop())
            carryover_tokens.append(token)

            # 現在の行を確定
            tokens_by_line.append(current_line_tokens)
            current_line_tokens = carryover_tokens

            # 初期化
            current_line_length = option.ENVIRON_LINE_INDENTATION_WIDTH + sum(
                [len(token.text) for token in current_line_tokens]
            )
        else:
            current_line_tokens.append(token)
```

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +                current_sentence_tokens = []
```python
        if token.text == "environ" or token.token_type == TokenType.COMMENT:
            current_sentence_tokens.append([token])
        else:
            current_sentence_tokens.append(token)
        if token.text == ";":
            output_tokens_by_sentence.append(current_sentence_tokens)
            current_sentence_tokens = []
```

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +        output_tokens_by_sentence.pop(0)
消す

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +            sys.exit(1)
tokenのline_number, column_numberを出力する

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +            )
```python
        # Adjust block level
        if first_token_text in option.INDENT_KEYWORDS:
            if not (current_block_type == "scheme" and first_token_text == "proof" and is_top_level_proof):
                # schemeブロックの最初のproof以外はblock levelを+1
                current_block_level += 1
        elif first_token_text == "end":
            current_block_level -= 1
        
        # Pre-indentation width
        if (current_block_type in ["theorem", "scheme"] and first_token_text == "proof" and is_top_level_proof or
            first_token_text in ["provided", "end"]):
            # theorem/schemeのブロック内で最初のproof，またはprovided/endであればインデントを-1
            current_indentation_step -= 1

        indentation_numbers.append(
            current_indentation_step * option.SPACE_NUMBER_PER_INDENTATION
        )

        # Post-indentation width
        if first_token_text in option.INDENT_KEYWORDS or first_token_text == "provided":
            # 字下げキーワードまたはprovided以降はインデントを+1
            current_indentation_step += 1

        if first_token_text == "proof":
            is_top_level_proof = False
```

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +            proof_found = False
is_top_level_proof = True

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +            proof_found = False
is_top_level_proof = True

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +    environ_part_tokens_by_line, body_part_tokens_by_line = split_into_environ_and_body_part(
environ -> envでも良い

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +    return indentation_numbers, output_tokens_by_line
```python
env_part_lines = format_env_part(env_part_token_lines)
body_part_lines = format_body_part(body_part_token_lines)
return env_part_lines + body_part_lines
```

2023-04-26 09:44 UTC, aabaa commented on src/miz_format.py
> +    return indentation_numbers, output_tokens_by_line
上位関数に移行する

2023-05-10 07:55 UTC, aabaa requested changes

2023-05-10 07:55 UTC, aabaa commented on src/miz_format.py
> +    space_adjusted_lines = generate_space_adjusted_lines(normalized_token_lines)
generate_space_adjusted_lines -> convert_token_lines_to_texts

2023-05-10 07:55 UTC, aabaa commented on src/miz_format.py
> +def split_line_at_max_length(line, indentation_width):
引数の説明コメントまたは型指定子を記載する．他同様．

2023-05-10 07:55 UTC, aabaa commented on src/miz_format.py
> +def split_line_at_max_length(line, indentation_width):
関数の説明でコメント行が80文字を超える場合は改行処理しない制限があることを明記する

2023-05-10 07:55 UTC, aabaa commented on src/miz_format.py
> +def split_env_part_token_lines_into_sentences(env_part_token_lines) -> list[list]:
関数の説明コメントを書く

2023-05-10 07:55 UTC, aabaa commented on src/miz_format.py
> +def adjust_newline_position(token_lines):
token_linesの型が分かるようにする

2023-05-10 07:55 UTC, aabaa commented on src/miz_format.py
> +                # LABEL: (":LABEL:", "theorem LABEL:" のパターンは除外)
"LABEL:"のパターンを抽出 (":LABEL:", "theorem LABEL:" のパターンは除外)

2023-05-13 06:25 UTC, raylicola commented
修正内容
- 関数名の修正
- コメントの修正・追記
- 関数の引数と返り値に型ヒントを追加
- adjust_newline_position の呼び出しを追加

2023-05-15 05:33 UTC, aabaa approved these changes

2023-05-15 05:33 UTC, merged